product_id: 0x0009 # RS485USB

joint_0_driver:
  joint_name: joint_0
  id: 3
  min_angle: -180
  max_angle:  180
  stretch: 60
  speed: 127
  current_limit: 3000
  temperature_limit: 80

joint_1_driver:
  joint_name: joint_0
  id: 4
  min_angle: -180
  max_angle:  180
  stretch: 60
  speed: 127
  current_limit: 3000
  temperature_limit: 80
