joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint_0_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_0
    
joint_1_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_1

joint_2_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_2

joint_3_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_3

joint_4_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_4

joint_5_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : arm_joint_5
